# Generated by Django 2.2.7 on 2019-11-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artists',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='moods',
            new_name='mood',
        ),
    ]
